# Generated by Django 5.0.3 on 2024-03-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_name_menu_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_item_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='title',
            new_name='name',
        ),
    ]
