# Generated by Django 5.0.3 on 2024-03-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu_item_description',
            new_name='description',
        ),
    ]
